### ISSUE TITLE
(front)[feature]: Definir a UX Design

### ISSUE THREAD

**Issue by suethttps** [fabricadesoftware-ifc/fabricaNews_frontEnd#3]
Fazer o estudo da experiência de usuário para um portal de noticias 

Usando as etapas:
- Arquitetura de Informação;
- Design de Interação;
- Design de serviços;
- Design Visual;

Basicamente pensar a maneira com que o usuário vai interagir com as coisas

**Comment by augussttos** [comment]
### Information architecture
- Organization systems: structures that show users where they are and where they want to go. It means that it's necessary to understand how we are gonna organize what is shown.
- Labeling systems: words that are used to represent information and concepts, the way we represent information and concepts. It's used to define and categorize content.
- Navigation systems: components that allow users to move through information. This includes: menus; breadcrumbs; buttons and links.
- Search systems: features that allows user to look for specific information. This includes: search box; filters.

###

**Comment by augussttos** [comment]
### Interaction design
- Goal-driven design: understand what the user needs to achieve, focus on the user's goals.
- Usability: make the product easy to use. It includes: intuitive interfaces; clear instructions; likelihood for errors.
- Affordances and signifiers: indicate how an object can be used.
- Feedback and response time: give the user a feedback about his action.
- Consistency: make the product easier to understand how to interact with it. It includes: consistent language; design elements; interaction patterns.
- Learnability: make the product easier to learn how to use it. Providing clear instructions or tutorials for more complex interactions.

**Comment by augussttos** [comment]
### Service design
- User journey: user's interaction with the product over time. 
- Touchpoints: specific interactions where users come into contact with the product.
- Frontstage and backstage: the frontstage refer the visible elements to users, therefore, backstage refer the non visible elements to users.
- Holistic approach: consider the entire experience of the user with the product, focusing in improve the product.

**Comment by augussttos** [comment]
### Visual design
- Typography: involves selection and use of fonts to enhance readability, hierarchy and visual appeal. It needs to be: legible; appropriate for the content; consistence through the design.
- Color: important for visual hierarchy, establishing brand identity and evoking specific emotions. Colors should be: intentional; accessibility; overall mood or tone the design aims to convey.
- Layout and composition: arrangement and placement of visual elements on a page screen. 
- Visual consistency: ensures that elements - such as buttons, icons and navigation - have a consistent look and behavior throughout the design. It includes making easier to navigate and understand the product.
- Visual imagery: use of imagery, such as photos, illustrations and icons to enhance the user experience and add visual interest.
- Whitespace and simplicity: whitespace is the empty space between elements. It helps creating visual balance, improves readability and provides visual breathing room. Simplicity in design involves eliminating unncessary clutter and focusing on essential elements to create a clean and intuitive interface.

**Comment by augussttos** [comment]
Suggestions for mobile apps inspirations:
- [Spotify](https://play.google.com/store/apps/details?id=com.spotify.music)
- [Twitter](https://play.google.com/store/apps/details?id=com.twitter.android)
- [Meliuz](https://play.google.com/store/apps/details?id=br.com.meliuz)
